apiVersion: apps/v1
kind: Deployment
metadata:
  name: myshop-client-depl
  #namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myshop-client
  template:
    metadata:
      labels:
        app: myshop-client
    spec:
      containers:
        - name: myshop-client
          image: arun6783/myshop-client:jwtdemo
          env:
            - name: OrchestratorUrl
              value: 'http://myshop-orchestrator-srv:6000'
            - name: REACT_APP_AUTH0_DOMAIN
              value: 'dev-gl3nsqil.us.auth0.com'
            - name: REACT_APP_AUTH0_CLIENT_ID
              value: 'cN2yCXHp26frXF3kYaDnq97kPcnwhuhQ'              
            - name: REACT_APP_AUTH0_AUDIENCE
              value: 'http://myshop-orchestrator-srv'
---
kind: Service
apiVersion: v1
metadata:
  name: myshop-client-srv
  #namespace: demo  
spec:
  selector:
    app: myshop-client
  ports:
    - name: http
      port: 8082
      targetPort: 8082
  # type: LoadBalancer
