# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dune-quote-service
#   annotations:
#     konghq.com/protocols: grpc
#     kubernetes.io/ingress.class: kong
# spec:
#   tls:
#     - secretName: grpc-secret
#       hosts:
#         - lotr.internal
#   rules:
#     - host: lotr.internal
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: lotr-grpc-srv
#                 port:
#                   number: 9001
