apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotr-node-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotr-node
  template:
    metadata:
      labels:
        app: lotr-node
    spec:
      containers:
        - name: lotr-node
          image: arun6783/lotr_node
          ports:
            - protocol: TCP
              containerPort: 9500
            - protocol: TCP
              containerPort: 9600
          volumeMounts:
            - mountPath: '/cert'
              name: my-secret
              readOnly: true

      volumes:
        - name: my-secret
          secret:
            secretName: my-secret
---
kind: Service
apiVersion: v1
metadata:
  name: lotr-node-srv
spec:
  selector:
    app: lotr-node
  ports:
    - name: http
      protocol: TCP
      port: 9500
      targetPort: 9500
    - name: https
      protocol: TCP
      port: 9600
      targetPort: 9600
#  type: LoadBalancer
