apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotr-grpc-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotr-grpc
  template:
    metadata:
      labels:
        app: lotr-grpc
    spec:
      containers:
        - name: lotr-grpc
          image: arun6783/lotr_grpc
          ports:
            - protocol: TCP
              containerPort: 9000
          env:
            - name: GRPC_PORT
              value: '9000'
            - name: SECURE_TLS
              value: 'yes'
            - name: DEBUG_CALLS
              value: 'true'
          volumeMounts:
            - mountPath: '/cert'
              name: my-secret
              readOnly: true

      volumes:
        - name: my-secret
          secret:
            secretName: my-secret
---
kind: Service
apiVersion: v1
metadata:
  name: lotr-grpc-srv
  annotations:
    # konghq.com/protocol: grpcs
spec:
  selector:
    app: lotr-grpc
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
  # type: LoadBalancer
