apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      containers:
        - name: aggregator
          image: arun6783/aggregator
          env:
            - name: SQUARE_HOST
              value: 'square-srv'
            - name: SQUARE_ROOT_HOST
              value: 'squareroot-srv'
            - name: SQUARE_PORT
              value: '4000'
            - name: SQUARE_GRPC_PORT
              value: '4500'
            - name: SQUARE_ROOT_PORT
              value: '5000'
            - name: USE_SSL
              value: 'false'
            - name: SQUARE_SSL_PORT
              value: '4443'
            - name: SQUARE_ROOT_SSL_PORT
              value: '5443'
            - name: SQUARE_ROOT_GRPC_PORT
              value: '5500'
---
kind: Service
apiVersion: v1
metadata:
  name: aggregator-srv
spec:
  selector:
    app: aggregator
  ports:
    - name: aggregator-tcp
      port: 3000
      targetPort: 3000
