apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simplemathingress
  annotations:
    konghq.com/preserve-host: 'false'
spec:
  ingressClassName: kong
  rules:
    - host: simplemathapp.web
      http:
        paths:
          - path: /(|static).*
            pathType: Prefix
            backend:
              service:
                name: simplemathapp-srv
                port:
                  number: 8082
