apiVersion: apps/v1
kind: Deployment
metadata:
  name: square-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: square
  template:
    metadata:
      labels:
        app: square
    spec:
      containers:
        - name: square
          image: arun6783/square
          env:
            - name: USE_SSL
              value: 'true'
---
kind: Service
apiVersion: v1
metadata:
  name: square-srv
spec:
  selector:
    app: square
  ports:
    - name: square-tcp
      port: 4000
      targetPort: 4000
    - name: square-https
      port: 4443
      targetPort: 4443
    - name: square-grpc
      port: 4500
      targetPort: 4500
