apiVersion: apps/v1
kind: Deployment
metadata:
  name: squareroot-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squareroot
  template:
    metadata:
      labels:
        app: squareroot
    spec:
      containers:
        - name: squareroot
          image: arun6783/squareroot
          env:
            - name: USE_SSL
              value: 'true'
---
kind: Service
apiVersion: v1
metadata:
  name: squareroot-srv
spec:
  selector:
    app: squareroot
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: grpc
      port: 5500
      targetPort: 5500
    - name: https
      port: 5443
      targetPort: 5443
