const data = [
  {
    height: '1.22m (4\'0")',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'April 6 ,2980',
    spouse: 'Rosie Cotton',
    death: 'Still alive, after going to the ,Undying Lands, in ,FO 61',
    quotes: [
      'There’s some good in this world, Mr. Frodo… and it’s worth fighting for.',
      "It's the job that's never started as takes longest to finish.",
      "But in the end it's only a passing thing, this shadow; even darkness must pass.",
      "I can't carry it for you, but I can carry you.",
    ],
    hair: 'Blond (movie)',
    name: 'Samwise Gamgee',
    wikiUrl: 'http://lotr.wikia.com//wiki/Samwise_Gamgee',
  },
  {
    height: '',
    race: 'Maiar',
    gender: 'Male',
    birth: 'Before the the Shaping of Arda',
    spouse: '',
    death: 'January 253019 ,Battle of the Peak immortal',
    quotes: [
      'Fly, you fools!',
      'When in doubt, follow your nose.',
      'The wise speak only of what they know.',
      'You shall not pass!',
      'A wizard is never late, Frodo Baggins. Nor is he early; he arrives precisely when he means to.',
    ],
    hair: 'Grey, later white',
    name: 'Gandalf',
    wikiUrl: 'http://lotr.wikia.com//wiki/Gandalf',
  },
  {
    height: 'Tall',
    race: 'Elf',
    gender: 'Male',
    birth: 'YT',
    spouse: 'Galadriel',
    death: 'Still alive, departed over the sea in the early Fourth Age',
    quotes: [
      'May it be a light to you in dark places, when all other lights go out.',
      'The Quest stands upon the edge of a knife. Stray but a little, and it will fail, to the ruin of all. Yet hope remains while the Company is true.',
      'All shall love me and despair!',
      'You may learn something, and whether what you see be fair or evil, that may be profitable, and yet it may not. Seeing is both good and perilous.',
      'For the time will soon come when Hobbits will shape the fortunes of all.',
    ],
    hair: 'Silver',
    name: 'Celeborn',
    wikiUrl: 'http://lotr.wikia.com//wiki/Celeborn',
  },
  {
    height: '',
    race: 'Dwarf',
    gender: 'Male',
    birth: 'TA 2879',
    spouse: '',
    death: 'Unknown (Departed to ,Aman ,FO 120,)',
    quotes: [
      'Memory is not what the heart desires. That is only a mirror.',
      'Faithless is he that says farewell when the road darkens.',
      'You are the luckiest, the canniest, and the most reckless man I ever knew.',
    ],
    hair: 'Auburn',
    name: 'Gimli',
    wikiUrl: 'http://lotr.wikia.com//wiki/Gimli',
  },
  {
    height: '198cm (6\'6")',
    race: 'Human',
    gender: 'Male',
    birth: 'March 1 ,2931',
    spouse: 'Arwen',
    death: 'FO 120',
    quotes: [
      'A hunted man sometimes wearies of distrust and longs for friendship.',
      'I can avoid being seen, if I wish, but to disappear entirely, that is a rare gift.',
      'Deeds will not be less valiant because they are unpraised.',
      'This day does not belong to one man but to all. Let us together rebuild this world that we may share in the days of peace.',
    ],
    hair: 'Dark',
    name: 'Aragorn II Elessar',
    wikiUrl: 'http://lotr.wikia.com//wiki/Aragorn_II_Elessar',
  },
  {
    height: '1.06m (3\'6")',
    race: 'Hobbit',
    gender: 'Male',
    birth: '22 September ,TA 2968',
    spouse: '',
    death: 'Unknown (Last sighting ,September 29 ,3021,) (,SR 1421,)',
    quotes: [
      'I will take the Ring, though I do not know the way.',
      'It is useless to meet revenge with revenge: it will heal nothing.',
    ],
    hair: 'Brown',
    name: 'Frodo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Frodo_Baggins',
  },
  {
    height: '1.25m (4\'1")',
    race: 'Hobbit',
    gender: 'Male',
    birth: '22 September ,TA 2890',
    spouse: 'None',
    death: 'Unknown (Last sighting 29 SeptemberTA 3021,) (,SR 1421,)',
    quotes: [
      'Don’t adventures ever have an end? I suppose not. Someone else always has to carry on the story.',
      "No, thank you! We don't want any more visitors, well-wishers or distant relations!",
      "I don't know half of you half as well as I should like, and I like less than half of you half as well as you deserve.",
      'It is no bad thing to celebrate a simple life.',
      "It's a dangerous business, Frodo, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.",
      'Not all those who wander are lost.',
      "I thought up an ending for my book: 'And he lived happily ever after, unto the end of his days.",
    ],
    hair: 'Brown, later white',
    name: 'Bilbo Baggins',
    wikiUrl: 'http://lotr.wikia.com//wiki/Bilbo_Baggins',
  },
  {
    height: '',
    race: 'Hobbit',
    gender: 'Male',
    birth: 'TA 2430',
    spouse: '',
    death: 'March 25 ,3019',
    quotes: [
      'We wants it, we needs it. Must have the precious. They stole it from us. Sneaky little hobbitses. Wicked, tricksy, false',
      'Well precious, if he looses, then we eats it!!',
      'My precious!',
      'Smeagol will swear on the Precious.',
      "Curse the Baggins! It's gone! What has it got in its pocketses?",
      "Misery misery! Hobbits won't kill us, nice hobbits.",
    ],
    hair: '',
    name: 'Gollum, Smeagol',
    wikiUrl: 'http://lotr.wikia.com//wiki/Gollum',
  },
]

exports.init_data = data
